services:
  postgres:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: arhome
      POSTGRES_USER: arhome
      POSTGRES_PASSWORD: arhome
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: arhome
      MINIO_ROOT_PASSWORD: arhome-development
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

volumes:
  postgres-data:
  minio-data:
